# Site settings
title: fernando's website
email: fdiaz094@fiu.edu
description: >-
  a personal site/blog
domain: "fediaz.me"
url: "https://fediaz.me"
twitter_username: nnnnnando
github_username:  fediazc
# Build settings
theme: minima
plugins:
  - jekyll-feed

