# Site settings
title: fernando's website
email: fdiaz094@fiu.edu
description: >-
  a personal site/blog
domain: "femdiaz.github.io"
url: "https://femdiaz.github.io"
twitter_username: nnnnnando
github_username:  femdiaz
# Build settings
theme: minima
plugins:
  - jekyll-feed

